import type { GalleryItem } from "@/content/types";

const galleryPath = "/images/mcgraw-made/gallery";
const printedPath = "/images/mcgraw-made/3d_printed";

export const galleryItems: GalleryItem[] = [
  {
    slug: "custom-cutting-board",
    title: "Engraved Welcome Board",
    category: "Personalized Gifts",
    caption: "A polished engraved board for housewarming, closing, or family gifting.",
    materials: "Engraved wood cutting board",
    repeatability: "Can Make Similar",
    ctaLabel: "Request Something Similar",
    ctaHref: "/custom-projects",
    imageLabel: "Engraved board",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-custom-cutting-board-01.jpg`,
    imageAlt: "Engraved custom cutting board with family name and home details",
  },
  {
    slug: "printed-herb-serving-tray",
    title: "Printed Herb Serving Tray",
    category: "UV Printed Items",
    caption: "A clean serving tray design with labeled herbs and crisp printed detail.",
    materials: "Printed tray, wood frame, side handles",
    repeatability: "Can Make Similar",
    ctaLabel: "Start a Custom Project",
    ctaHref: "/custom-projects",
    imageLabel: "Printed tray",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-printed-herb-serving-tray-04.jpg`,
    imageAlt: "White serving tray printed with herb illustrations and labels",
  },
  {
    slug: "engraved-club-plaque",
    title: "Engraved Club Plaque",
    category: "Awards & Plaques",
    caption: "Dimensional plaque work for teams, clubs, and recognition moments.",
    materials: "Layered wood with engraved and painted details",
    repeatability: "Can Make Similar",
    ctaLabel: "Request a Plaque",
    ctaHref: "/custom-projects",
    imageLabel: "Logo plaque",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-engraved-club-plaque-05.jpg`,
    imageAlt: "Round engraved club plaque with high-contrast layered detail",
  },
  {
    slug: "floral-name-sign",
    title: "Floral Name Sign",
    category: "Signs & Decor",
    caption: "Soft nursery or bedroom decor with layered florals and raised lettering.",
    materials: "Painted wood, raised lettering, layered floral accents",
    repeatability: "Can Make Similar",
    ctaLabel: "Request a Name Sign",
    ctaHref: "/custom-projects",
    imageLabel: "Name sign",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-floral-name-sign-06.jpg`,
    imageAlt: "Round floral name sign with pink raised lettering",
  },
  {
    slug: "round-baby-name-sign",
    title: "Baby Name Sign",
    category: "Family Keepsakes",
    caption: "A personalized round sign for nursery styling and baby milestones.",
    materials: "Layered wood and painted dimensional accents",
    repeatability: "Can Make Similar",
    ctaLabel: "Request Something Similar",
    ctaHref: "/custom-projects",
    imageLabel: "Nursery sign",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-round-baby-name-sign-07.jpg`,
    imageAlt: "Round baby name sign with dimensional lettering and floral accents",
  },
  {
    slug: "puerto-rico-custom-sign",
    title: "Puerto Rico Custom Sign",
    category: "Custom Fabrication",
    caption: "A detailed dimensional sign that shows range, color, and fabrication complexity.",
    materials: "Layered wood, painted finish, raised details",
    repeatability: "Past Work Only",
    ctaLabel: "Start a Custom Project",
    ctaHref: "/custom-projects",
    imageLabel: "Custom sign",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-puerto-rico-custom-sign-08.jpg`,
    imageAlt: "Dimensional Puerto Rico custom sign with layered city names and color",
  },
  {
    slug: "personalized-family-tray",
    title: "Personalized Family Tray",
    category: "Personalized Gifts",
    caption: "A refined home piece with monogram detail and a family-name centerpiece.",
    materials: "Painted tray, engraved detail, metal handles",
    repeatability: "Can Make Similar",
    ctaLabel: "Request a Custom Tray",
    ctaHref: "/custom-projects",
    imageLabel: "Family tray",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-personalized-family-tray-10.jpg`,
    imageAlt: "Personalized gray family tray with monogram and laurel engraving",
  },
  {
    slug: "shield-logo-plaque",
    title: "Shield Logo Plaque",
    category: "Awards & Plaques",
    caption: "A logo-forward plaque for organizations, clubs, teams, and events.",
    materials: "Layered wood, engraved logo detail, stained finish",
    repeatability: "Can Make Similar",
    ctaLabel: "Request a Plaque",
    ctaHref: "/custom-projects",
    imageLabel: "Shield plaque",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-shield-logo-plaque-11.jpg`,
    imageAlt: "Square shield-style custom logo plaque with layered lettering",
  },
  {
    slug: "safari-nursery-name-sign",
    title: "Safari Nursery Sign",
    category: "Signs & Decor",
    caption: "Dimensional nursery decor with playful detail and a finished gift feel.",
    materials: "Layered wood, painted accents, raised name lettering",
    repeatability: "Can Make Similar",
    ctaLabel: "Request a Name Sign",
    ctaHref: "/custom-projects",
    imageLabel: "Nursery decor",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-safari-nursery-name-sign-12.jpg`,
    imageAlt: "Round safari nursery sign with animal accents and raised name lettering",
  },
  {
    slug: "custom-van-event-sign",
    title: "Custom Event Sign",
    category: "Custom Fabrication",
    caption: "A colorful event piece that shows custom illustration, shape, and brand personality.",
    materials: "Layered wood with painted and printed details",
    repeatability: "Can Make Similar",
    ctaLabel: "Start a Custom Project",
    ctaHref: "/custom-projects",
    imageLabel: "Event sign",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-custom-van-event-sign-14.jpg`,
    imageAlt: "Custom van-shaped event sign with bright orange and blue details",
  },
  {
    slug: "lakeland-award-medal",
    title: "Lakeland Award Medal",
    category: "Awards & Plaques",
    caption: "A clean award piece with engraved detail for shows, teams, and recognition.",
    materials: "Engraved wood medal with cut profile",
    repeatability: "Can Reorder",
    ctaLabel: "Request Awards",
    ctaHref: "/custom-projects",
    imageLabel: "Award medal",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-lakeland-award-medal-15.jpg`,
    imageAlt: "Engraved Lakeland best in show award medal",
  },
  {
    slug: "engraved-comb-brush-keepsake",
    title: "Engraved Grooming Keepsake",
    category: "Personalized Gifts",
    caption: "A personal keepsake that shows small-format engraving and thoughtful detail.",
    materials: "Engraved wood comb and brush",
    repeatability: "Can Make Similar",
    ctaLabel: "Request a Keepsake",
    ctaHref: "/custom-projects",
    imageLabel: "Keepsake",
    imageSrc: `${galleryPath}/mcgraw-made-gallery-engraved-comb-brush-keepsake-16.jpg`,
    imageAlt: "Engraved wooden comb and brush keepsake set",
  },
  {
    slug: "3d-printed-mini-bookshelf",
    title: "3D Printed Mini Bookshelf",
    category: "3D Printed Items",
    caption:
      "A decorative miniature bookshelf that shows small-format printing, detail, and display value.",
    materials: "3D printed shelf with miniature printed book details",
    repeatability: "Can Make Similar",
    ctaLabel: "Request 3D Printed Items",
    ctaHref: "/custom-projects",
    imageLabel: "3D print",
    imageSrc: `${printedPath}/mcgraw-made-3d-printed-mini-bookshelf-01.jpg`,
    imageAlt: "3D printed mini bookshelf filled with miniature books",
  },
];
