import type { GalleryItem } from "@/content/types";

export const galleryItems: GalleryItem[] = [
  {
    slug: "family-name-plaque",
    title: "Layered Family Name Plaque",
    category: "Signs & Decor",
    caption: "Warm wood tones with raised lettering for a front entry statement.",
    materials: "Painted wood, layered acrylic accents",
    repeatability: "Can Make Similar",
    ctaLabel: "Request Something Similar",
    ctaHref: "/custom-projects",
    imageLabel: "Layered plaque",
  },
  {
    slug: "sports-banquet-awards",
    title: "Sports Banquet Awards",
    category: "Awards & Plaques",
    caption: "Clean presentation pieces designed for team recognition and sponsor events.",
    materials: "Acrylic, walnut finish base, engraved plate",
    repeatability: "Can Reorder",
    ctaLabel: "Request This Item",
    ctaHref: "/custom-projects",
    imageLabel: "Award set",
  },
  {
    slug: "bridal-party-gift-set",
    title: "Bridal Party Gift Set",
    category: "Personalized Gifts",
    caption: "Coordinated keepsakes built around names, dates, and event colors.",
    materials: "Mixed materials, laser engraving, UV print",
    repeatability: "Can Make Similar",
    ctaLabel: "Request Something Similar",
    ctaHref: "/custom-projects",
    imageLabel: "Gift set",
  },
  {
    slug: "holiday-centerpiece",
    title: "Holiday Table Centerpiece",
    category: "Seasonal Items",
    caption: "A seasonal display piece designed for repeat festive styling.",
    materials: "Layered wood, metallic paint accents",
    repeatability: "Past Work Only",
    ctaLabel: "Start a Custom Project",
    ctaHref: "/custom-projects",
    imageLabel: "Holiday centerpiece",
  },
  {
    slug: "teacher-door-sign",
    title: "Teacher Door Sign",
    category: "Signs & Decor",
    caption: "Bright, personality-forward signage for classrooms and studios.",
    materials: "Wood composite, sealed paint finish",
    repeatability: "Can Reorder",
    ctaLabel: "Request This Item",
    ctaHref: "/custom-projects",
    imageLabel: "Door sign",
  },
  {
    slug: "event-favor-tags",
    title: "Event Favor Tags",
    category: "UV Printed Items",
    caption: "Small-format pieces that elevate event packaging and guest details.",
    materials: "UV printed acrylic tags",
    repeatability: "Can Make Similar",
    ctaLabel: "Request Something Similar",
    ctaHref: "/custom-projects",
    imageLabel: "Favor tags",
  },
];
