import type { ReadyMadeItem } from "@/content/types";

const readyMadePath = "/images/mcgraw-made/ready_made";

export const readyMadeItems: ReadyMadeItem[] = [
  {
    slug: "holiday-activity-jar",
    title: "Holiday Activity Jar",
    category: "Seasonal Gifts",
    description:
      "A ready-to-gift jar filled with activity tokens for simple holiday moments at home.",
    price: "$28",
    availability: "Made-to-Order Available",
    quantityLabel: "Available in small seasonal runs",
    fulfillmentNote: "Use the Square link when active, or inquire for the next available run.",
    materials: "Glass jar, engraved wood activity tokens, printed lid detail",
    squareLink: "https://square.link/u/placeholder-holiday-activity-jar",
    squareLinkLabel: "Buy Now",
    imageLabel: "Gift jar",
    imageSrc: `${readyMadePath}/mcgraw-made-ready-made-holiday-activity-jar-04.jpg`,
    imageAlt: "Holiday activity jar with engraved wood activity tokens",
  },
  {
    slug: "winter-paint-kit",
    title: "Winter Paint Kit",
    category: "Kids & Family Gifts",
    description:
      "A shelf-ready paint kit with a wood winter sign, paints, and brushes included.",
    price: "$22",
    availability: "Available",
    quantityLabel: "Limited finished kits available",
    fulfillmentNote: "Ready for local pickup or shipping while supplies last.",
    materials: "Laser-cut wood sign, paints, brushes, seasonal printed card",
    squareLink: "https://square.link/u/placeholder-winter-paint-kit",
    squareLinkLabel: "Buy Now",
    imageLabel: "Paint kit",
    imageSrc: `${readyMadePath}/mcgraw-made-ready-made-winter-paint-kit-05.jpg`,
    imageAlt: "Hello winter wood paint kit with paints and brushes",
  },
  {
    slug: "roll-the-dice-gift-game",
    title: "Roll the Dice Gift Game",
    category: "Party Gifts",
    description:
      "A simple exchange-game set designed for holiday parties, family nights, and gifting.",
    price: "$18",
    availability: "Available",
    quantityLabel: "Small batch available now",
    fulfillmentNote: "Ready to ship or coordinate pickup this week.",
    materials: "Printed wood tags, ribbon, game dice",
    squareLink: "https://square.link/u/placeholder-roll-the-dice-game",
    squareLinkLabel: "Buy Now",
    imageLabel: "Gift game",
    imageSrc: `${readyMadePath}/mcgraw-made-ready-made-roll-the-dice-game-06.jpg`,
    imageAlt: "Roll the dice gift exchange game tags with ribbon and dice",
  },
  {
    slug: "santa-tracker-ornaments",
    title: "Santa Tracker Ornaments",
    category: "Seasonal Gifts",
    description:
      "Colorful Santa tracker ornaments with layered details and scannable holiday fun.",
    price: "$14",
    availability: "Made-to-Order Available",
    quantityLabel: "Made in seasonal batches",
    fulfillmentNote: "Purchase or inquire during the holiday run window.",
    materials: "Layered wood, printed detail, hanging cord",
    squareLink: "https://square.link/u/placeholder-santa-tracker-ornaments",
    squareLinkLabel: "Buy Now",
    imageLabel: "Ornaments",
    imageSrc: `${readyMadePath}/mcgraw-made-ready-made-santa-tracker-ornaments-07.jpg`,
    imageAlt: "Colorful Santa tracker ornaments arranged on a dark tabletop",
  },
  {
    slug: "wine-slate-coasters",
    title: "Wine Slate Coasters",
    category: "Home Gifts",
    description:
      "A polished coaster set for host gifts, wine nights, and ready-made home gifting.",
    price: "$32",
    availability: "Low Stock",
    quantityLabel: "Limited finished sets available",
    fulfillmentNote: "Ready for pickup or shipping while the current set lasts.",
    materials: "Engraved slate coasters",
    squareLink: "https://square.link/u/placeholder-wine-slate-coasters",
    squareLinkLabel: "Buy Now",
    imageLabel: "Coaster set",
    imageSrc: `${readyMadePath}/mcgraw-made-ready-made-wine-slate-coasters-09.jpg`,
    imageAlt: "Set of engraved slate wine coasters",
  },
];
